### ISSUE TITLE
What Algorithm is this Package Based On?

### ISSUE THREAD

**Issue by LukaTandaric** [i-cyto/cytoBatchNorm#2]
Dear Sam,

I had first intended on using the CytofBatchAdjust package to try and batch correct my CyTOF data.
[However, you directed me towards this GUI built on top of CytofBatchAdjust.](https://github.com/CUHIMSR/CytofBatchAdjust/issues/9#issuecomment-1385947130)

I am unable to find any publications describing the coneptualization and mechanistics of this package,
like I can for [CytofBatchAdjust](https://www.frontiersin.org/articles/10.3389/fimmu.2019.02367/full), only that "It is inspired from the cytofBatchAdjust script and the cytoNorm package.",
is written in the [description file](https://github.com/i-cyto/cytoBatchNorm/blob/main/DESCRIPTION). 

Knowing this is very important for my work and publications.

Could you please elaborate on those aspects of cytoBatchNorm?

Kind regards.
Luka

**Comment by SamGG** [comment]
Dear Luka,

We have resubmitted an article but didn't get an answer yet. As this package is using the same formula as CytofBatchAdjust, an article describing its use and benefits have not attracted the interest of editors currently.

Let's summarize the formula of Schuyler et al. (mass cytometry data, I am not even sure they gave a formula, @CUHIMSR correct me if I am wrong).

First, a short reminder of the experimental design:
- there is a reference sample in each batch that is labelled at the same time as the other samples
- this reference sample is usually an aliquot of a larger sample
- this reference sample permits to design a per channel correction that is applied to the rest of the samples of the same batch
- all reference samples samples are aligned to the reference sample of the reference batch (unique for the whole experiment, chosen by the experimenter)

Let's focus on a single channel, as the method is identical for all the channels:
- a formula is defined for each batch, is based on the reference sample of the batch, and aims to align the reference file of the batch to the reference file of the reference batch; to be exact, the aim is to align the distribution of the intensity of the channel.
- the formula (aka correction) is a linear scaling: corrected_intensity = coeff * intensity
- coeff is based on the single percentile selected by the user: coeff = intensity_at_the_percentile_in_the_reference_file_of_the_reference_batch / intensity_at_the_percentile_in_the_reference_file_of_the_current_batch
- the percentile permits to retrieve the corresponding intensity
- the formula is defined on the reference files and then applied the rest of the files in their own batch

Our package:
- provides a graphical user interface (GUI) for all the steps of the procedure
- allows to select a specific percentile for each channel; there is no unique percentile for all the channels
- eases the selection of the percentile by providing a graphics that shows the percentile across all the reference files (ie all the batches); the percentile is usually chosen to identify the top of the positive peak in the distribution of the intensities of the channel, or a specific characteristic on a decreasing slope
- permits to visualize the result of the correction applied to each reference, and to judge of the relevance of the chosen percentile or, after multiple trials, of the real need to apply any correction
- permits to visualize the corrected intensities in a bi-plot; as shown by Schuyler et al., there could be artifacts due to the fact that channels are treated independently
- permits to visualize coeff across all batches; same as CytofBatchAdjust
- permits to visualize the correction function; similar to CytoNorm in a big pdf (IIRC)

All the visualizations are presenting in transformed intensities, ie asinh(raw_intensity/cofactor), but the formula is applied either on the raw intensity or the transformed intensity (as proposed by Schuyler et al.).

There is a good overview of the pros and cons of each algorithm in paragraph 3.4 of "Key steps and methods in the experimental design and data analysis of highly multi-parametric flow and mass cytometry" from Rybakowska et al. https://doi.org/10.1016/j.csbj.2020.03.024
P. Rybakowska published an article describing the steps of a pipeline including the batch normalisation. https://www.sciencedirect.com/science/article/pii/S2666166722005779?via%3Dihub
This pipeline is using a simpler version of CytoNorm by selecting two quantiles (alias percentiles) only  https://github.com/prybakowska/CyTOF_analysis_Pipeline1/blob/701b992e1ab8810c06be295b4b59fe2eba31915d/pipeline.R#L353 instead of using 101 quantiles 
https://github.com/saeyslab/CytoNorm/blob/b350864d498154f2779cf94fbb97691cc7b3ec2a/R/QuantileNorm.R#L148
without FlowSOM step IIRC

All in one, there is a good rational in using one or two quantiles. Two quantiles is also possible in our package, and the formula is simply: corrected_intensity = coeff * intensity + offset or in detail
corrected_int = (int_top_ref - int_bot_ref) / (int_top_batch - int_bot_batch) * (int - int_bot_batch) + int_bot_ref
where
_batch refers to one batch
_ref refers to the reference batch
_bot (resp. _top) refers to the low (resp. high) quantile
Check step 7 of figure 3 of pipeline of P. Rybakowska et al.

I hope this will help you. Let me know.

All the best,
Samuel

**Comment by LukaTandaric** [comment]
Dear @SamGG,

thank you for this overview of the logic behind this tool.
It has helped me contextualize things nicely.

Kind regards.
Luka
